site_name: Planet API Client
site_description: Python client library and CLI for Planet's public API.
site_url: https://planetlabs.github.io/planet-client-python/

theme:
    name: 'material'

repo_name: planetlabs/planet-client-python
repo_url: https://github.com/planetlabs/planet-client-python
edit_uri: ""

nav:
    - Developer Interface: 'api.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
